name: deploy

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 352835053263

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: git config -l
      - name: Install
        run: npm ci
      - name: Version
        run: npx lerna version --yes
      - name: Audit
        run: npm audit
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build

  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Assume OIDC Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/oidc-provider-role
          role-session-name: gh-infrastructure-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      - name: Synth
        run: npx nx run @actions/apps-infrastructure:cdk:synth -- --require-approval never
      - name: Deploy
        run: npx nx run @actions/apps-infrastructure:cdk:deploy -- --require-approval never

  dev:
    runs-on: ubuntu-latest
    needs: [build, infrastructure]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Assume OIDC Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/oidc-provider-role
          role-session-name: gh-dev-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy CDK
        run: npx nx affected -t dev:cdk:deploy
      - name: Deploy
        run: npx nx affected -t dev:deploy

  prod:
    if: github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    needs: [dev]
    steps:
      - name: Deploy
        run: echo 'Deployed prod'
