name: deploy

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 352835053263

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true
        default: 'dev'

jobs:
  dev:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: 'Deploy infrastructure'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/oidc-provider-role
          role-session-name: gh-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      - run: npx nx run @actions/apps-infrastructure:cdk:synth -- -c env=dev --require-approval never
      - run: npx nx run @actions/apps-infrastructure:cdk:deploy -- -c env=dev --require-approval never
      - name: Deploy app
        run: echo 'Deployed dev'

  prod:
    if: github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    needs: [dev]
    steps:
      - name: Deploy
        run: echo 'Deployed prod'
