name: deploy

on:
  workflow_run:
    workflows: [pull-request]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true
        default: 'dev'

jobs:
  dev:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Deployed dev'

  prod:
    if: github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    needs: [dev]
    steps:
      - name: Deploy
        run: echo 'Deployed prod'
