name: deploy

env:
  NODE_VERSION: 20
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 352835053263

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: string
        required: true
        default: 'dev'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Assume OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/oidc-provider-role
          role-session-name: gh-dev-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy CDK
        run: npx nx affected -t ${{ inputs.environment }}:cdk-deploy

