name: infrastructure

env:
  NODE_VERSION: 20
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 352835053263

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '!**/*.md'

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install
        run: npm ci
      - name: Build
        working-directory: ./infrastructure
        run: |
          npm run lint
          npm run build
      - name: Assume OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/oidc-provider-role
          role-session-name: gh-infrastructure-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      - name: Synth
        working-directory: ./infrastructure
        run: npm run cdk:synth -- --require-approval never
      - name: Deploy
        working-directory: ./infrastructure
        run: npm run cdk:deploy -- --require-approval never
