name: pull request

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install
        run: npm i
      - name: Audit
        run: npm audit
      - name: Lint
        run: npx nx affected -t lint
      - name: Test
        run: npx nx affected -t test
      - name: Build
        run: npx nx affected -t build
