name: pull-request

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install
        run: npm i
      - name: Audit
        run: npm audit
      - name: Lint
        run: npx nx affected -t lint --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }}
      - name: Test
        run: npx nx affected -t test --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }}
      - name: Build
        run: npx nx affected -t build --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }}
